rr-/szurubooru

gruntfile.js

I fixed invalid `mousetrap` lib path in `gruntfile.js` (uppercase instead of lowercase). 
`grunt copy` was executing without errors even though `mousetrap` lib was not copied which resulted in blank page.

Fix mousetrap library path

---

client/build.js
client/package-lock.json
client/package.json

The `harmony`-branch is now its own package called `uglify-es`, which isn't backwards-compatible and breaks the build.
Using a non-ES6 version of `2.x` seems to work fine for now.

Fix build, use uglify-es package directly

---

client/html/help_keyboard.tpl

There are some spelling issues in the `Help`→`Keyboard` section (some missing articles and _Shift_ is spelled incorrectly).

Spelling issues in Help→Keyboard

---

client/js/controls/post_content_control.js
client/js/views/home_view.js

The featured post should always use the "both" resize mode in the home view regardless of what the user has set in the post view.
This resolves #144.

Override resize mode in home view

---

server/szurubooru/func/images.py

* Poorly formatted MP4 and WEBM sources can cause ffmpeg to throw a lot of warnings. However when there is byte ouptut, the generated thumbnail is valid. Add a bypass for the resize_fill function to allow ffmpeg to error.
* Simplify the ffmpeg video filter scaling parameter

Allow thumbnails to be generated even if ffmpeg throws warnings

---

client/js/models/post.js
client/js/views/post_upload_view.js

Issue #153 seems to be because the API expects a list of tag names, but the client is sending the entire list of tag objects when Copy tag is selected on the upload dialog for the similar images. This resulted in ctx.get_param_as_string_list method iterating over objects that weren't strings and returning the "Parameter ‘tags’ must be a list of string values" error message.
I think the simplest fix is to add a get method to the post object to retrieve a list of the tag names. Referencing only the first name in the list of names for a tag seems to be the current practice for identifying the primary name for a tag.

client/posts: fix copy tags list of string values error #153

---

client/js/views/post_upload_view.js

Anonymous node does not exist in view when a user without anonymous upload permission tries to post upload. So in this case we should check for the existence of anonymousNode first.

client/posts: fix upload error caused by anonymous node

---

client/js/api.js
client/js/controllers/home_controller.js
client/js/controllers/post_list_controller.js
client/js/controllers/post_upload_controller.js
client/js/controllers/top_navigation_controller.js
client/js/controllers/user_controller.js
client/js/controls/post_edit_sidebar_control.js
client/js/controls/post_readonly_sidebar_control.js
client/js/main.js
client/js/models/post_list.js
client/js/models/top_navigation.js
client/js/views/help_view.js
client/js/views/login_view.js
client/js/views/not_found_view.js
client/js/views/password_reset_view.js
client/js/views/post_merge_view.js
client/js/views/registration_view.js
client/js/views/tag_edit_view.js
client/js/views/tag_merge_view.js
client/js/views/user_edit_view.js
server/szurubooru/api/info_api.py

Per #168 
Most of the needed client-side configurations, including the privileges table, regular expression filters, app title, and contact info, are fetched using the backend's Info API now. 
The hope is that this will greatly simplify the build/deployment process, especially for Docker users, as it will be possible to build the frontend before many of the configurations are set.
I have a modified `build.js` that I'm working on, but I'm excluding it from this PR (for now) as it would alter the build/deployment process for existing users. Right now, this PR should work as a drop-in change and end users won't have to change anything about their deployment process.

Get client-side configuration at runtime

---

client/.babelrc
client/build.js
client/package-lock.json
client/package.json

I've updated all the dependencies and replaced `uglify-es` with [`terser`](https://github.com/fabiosantoscode/terser) (a hard fork of uglify-es, which is apparently no longer actively maintained). The updates got rid of any security issues `npm audit` would report (there were over 300 minor issues before iirc). This closes #174 and closes #175.
Next, I've replaced `babel-preset-es-2015` with `babel-preset-env`. In the near future, we may want to upgrade to [Babel 7](https://babeljs.io/docs/en/next/v7-migration), but that's still in beta so I've left it out for now.
I've also gone ahead and split up the dependencies into regular `dependencies` (which are required for the application to run) and `devDependencies` (which are just required for the build). It doesn't matter right now since npm …

client/build: replace uglify-es, update dependencies

---

INSTALL.md
client/Dockerfile
client/build.js
client/css/core-general.styl
client/css/post-content-control.styl
client/html/index.htm
client/js/api.js
client/js/controllers/top_navigation_controller.js
client/js/models/top_navigation.js
client/js/router.js
client/js/util/uri.js
server/szurubooru/config.py

This allows users to specify a different URI prefix other than `/`: e.g serve the web application on something like `http://example.com/mybooru/` instead of just `http://example.com/`. This allows users to serve mutiple web applications off the same domain name.
This basically leverages on using the HTML `<base>` tag. Docker users set the base href with a `BASE_URL` environment at runtime, while non-docker users can pass it to the `build.js` script. The base href defaults to `/`, so this shouldn't affect the deployment of any existing users. 
The biggest changes were made to `router.js` which reads the base tag from the DOM to figure out the proper routing URIs. The rest of the changes mostly consist of just dropping the leading slash from any URIs to make the base tag work.
For testing: …

Added feature: Specify Base URIs other than `/`

---

client/html/post_merge_side.tpl
client/html/post_readonly_sidebar.tpl

Posts with MIME type `video/mp4` would either show the content format as undefined or not at all. This fixes that.

client: Stop showing mp4 files as undefined

---

client/html/help_search_posts.tpl
client/html/post_edit_sidebar.tpl
client/html/post_readonly_sidebar.tpl
client/js/controls/post_edit_sidebar_control.js
server/szurubooru/api/post_api.py
server/szurubooru/func/images.py
server/szurubooru/func/posts.py
server/szurubooru/func/snapshots.py
server/szurubooru/migrations/versions/1cd4c7b22846_change_flags_column_to_string.py
server/szurubooru/model/post.py
server/szurubooru/search/configs/post_search_config.py

A lot GIF-like video loops (GFYs or whatever people usually call them) on the internet nowadays come with sound. This allows users to add a sound flag to video posts so that others can know if a post has sound before playing a clip.
First commit enables a sound flag on the backend, shows if it's present in the post view, and allows for setting during upload and post edit.
Second commit allows for flags to be searched, with `flag:sound` and `flag:loop`. The best way to do this was to migrate the flags column in the post table from PickleType/binary to varchar, stored as a comma delimited list. This allows for the column to be queried easily (I'm not sure if it's even possible to query a PickleType in SQLAlchemy, as I can't find any documentation or examples) and also has the side benefit …

New flag: check sound

---

client/css/core-general.styl
client/css/post-content-control.styl

The patch made in #220 does not work if `BASE_URI` is set to anything but the default value. This still fixes the original issue while keeping the URI path relative, so that it is compatible with all base URIs

Fix transparency grid for alternate base URIs

---

client/html/post_edit_sidebar.tpl
client/html/post_readonly_sidebar.tpl
client/js/controllers/post_main_controller.js
client/js/controls/post_edit_sidebar_control.js
client/js/models/post.js
client/js/util/uri.js

Revisiting the stale PR #215 ( which closes #204 ) with some additional fixes. 
The source field is hidden completely on the view sidebar if unset. The source field will only display the host domain to look more readable. So a source of `http://example.com/image?id=foobar` will display as
> Source: [example.com](http://example.com/image?id=foobar)
on the view sidebar. Additionally a tooltip will show the full URL on hover.

client: Reimplement post source functionality

---

client/html/post_readonly_sidebar.tpl
client/html/posts_page.tpl

Adds a 'loop' icon in the post view sidebar to indicate if the loop flag is set, similar to how there's an icon to indicate if the sound flag is set.
Also, in the post listing page, the labels 'video', 'animation', and 'flash' have been replaced with [this icon](https://fontawesome.com/v4.7.0/icon/film), which looks cleaner IMO

client/posts: Add some UI icons

---

client/html/help_search_posts.tpl
server/szurubooru/search/configs/post_search_config.py

Allows searching for posts by source URL.
You can use either something like `source:twitter` to find all all twitter related posts or `source:twitter.com/some-specific-url` for specific URL queries.

Add source searching

---

client/js/util/touch.js
client/js/views/post_main_view.js

#243
* Add util/touch.js to abstract the swipe implementation, with support for left, right, up and down baked in.
* Update views/post_main_view to instantiate a new Touch instance to handle left and right swipes on the post image.

client/post: Add swipe left and swipe right gestures to post content

---

server/requirements.txt

It seems that Elasticsearch version 7.0.0 introduced a breaking change, which caused #248 
Updated server requirements.txt

server/build: Ensure elasticsearch library is a compatible version

---

client/html/post_readonly_sidebar.tpl
client/html/settings.tpl
client/html/tag.tpl
client/js/controls/post_readonly_sidebar_control.js
client/js/models/settings.js
client/js/util/misc.js
client/js/util/views.js
client/js/views/settings_view.js
client/js/views/tag_view.js

Fixes #258
Honestly I'm not a huge fan of how this turned out, especially with the 'global' tagUnderscoresAsSpaces variable in `util/misc.js`, but this is the best thing I could come up with to avoid calling `settings.get()` multiple times (which is a somewhat expensive call).
I also didn't fully comment my code as that wasn't done anywhere else in the project so I couldn't copy a documentation style.
This setting is disabled by default, so nothing changes for existing users.

Add setting to display underscores as spaces in tags

---

docker-compose.yml

this sets the ulimits for elasticsearch to the recommended value of 65536 to avoid errors on startup.

docker: set ulimits for elasticsearch

---

client/js/controllers/auth_controller.js

When the tag category list permission is not anonymous the category colors fail to load if you are not logged in, and because the page doesn't reload (SPA) the tag colors are still broken after logging in. Manually calling refreshCategoryColorMap after logging in solves this issue.
Should fix last issue discussed in #269

client/auth: call tags.refreshCategoryColorMap() after login

---

server/szurubooru/func/mime.py

Some videos weren't detected as mp4.
Example:
http://paste.c-net.org/ComedianTangle
Relevant part of the mimetype info:
`Codec ID                                 : iso5 (avc1/iso5/dsms/msix/dash)
`

detect ftypiso5 as mp4 mime type

---

doc/INSTALL.md
docker-compose.yml
server/Dockerfile
server/config.yaml.dist
server/hooks/test
server/requirements.txt
server/szurubooru/api/post_api.py
server/szurubooru/config.py
server/szurubooru/facade.py
server/szurubooru/func/image_hash.py
server/szurubooru/func/posts.py
server/szurubooru/migrations/versions/52d6ea6584b8_generate_post_signature_table.py
server/szurubooru/model/__init__.py
server/szurubooru/model/post.py
server/szurubooru/tests/api/test_post_creating.py
server/szurubooru/tests/api/test_post_updating.py
server/szurubooru/tests/conftest.py
server/szurubooru/tests/func/test_image_hash.py
server/szurubooru/tests/func/test_posts.py
server/szurubooru/tests/model/test_post.py

Hey, @rr- , I would like you to review this before I merge it in.
This basically moves the reverse image search functionality that relied on Elasticsearch into Postgres, which was surprisingly easy. I test ran it on a copy of my personal instance (with about 4k images) and it seems to have similar performance to Elasticsearch as well, while being much more lightweight.
Only thing that feels a bit hacky to me is that I had to write raw SQL for the image search query. It seems like SQLAlchemy doesn't have a full implementation of Postgres' `unnest` function:
https://groups.google.com/forum/#!msg/sqlalchemy/thc9rla91gU/uFpXTAFKAwAJ

Migrate Elasticsearch functionality into Postgres

---

server/szurubooru/migrations/versions/1e280b5d5df1_longer_tag_names.py
server/szurubooru/model/snapshot.py
server/szurubooru/model/tag.py

Because some series are called itai_no_wa_iya_nano_de_bougyoryoku_ni_kyokufuri_shitai_to_omoimasu.
128 seemed like the most logical number after 64. I guess 80 or something like that would suffice, but then we might have another PR in 4 months. Space-wise it doesn't actually matter.

server/func/tags: allow tags to have longer names

---

README.md
client/html/post_upload_row.tpl
client/js/views/post_upload_view.js
doc/API.md
server/Dockerfile
server/config.yaml.dist
server/szurubooru/api/post_api.py
server/szurubooru/api/upload_api.py
server/szurubooru/errors.py
server/szurubooru/func/net.py
server/szurubooru/func/posts.py
server/szurubooru/rest/context.py
server/szurubooru/tests/api/test_post_creating.py
server/szurubooru/tests/api/test_post_updating.py
server/szurubooru/tests/func/test_net.py
server/szurubooru/tests/rest/test_context.py

- Allows for video-based posts to be created by using youtube-dl.  Now you can directly pass a URL to a site containing a video file (youtube, gfycat, etc) to generate a video post, instead of having to find a hotlink to the .mp4/.webm file (if one even exists).
- While convenient, there is potential for abuse of this feature, so a new permission "uploads:use_downloader" has been created, defaulting to power users and above.
- Default flag behavior has been changed globally (to partially support this). When using the web interface, the "loop" flag is set by default for all video posts. Users accessing the API directly can circumvent the defaults by ensuring that the `flag` parameter is set in the request.

Allow for fetching post content with youtube-dl

---

server/requirements.txt

If the current requirements.txt is used and deployed in the on-premises environment, SQLAlchemy 1.4 series will be introduced and the test will not pass due to compatibility issues.
Therefore, we need to suppress the use of SQLAlchemy 1.4.

Suppressed the use of SQLAlchemy 1.4

---

client/css/core-general.styl
client/css/pager.styl
client/css/post-main-view.styl
client/css/tag-input-control.styl
client/js/controls/tag_input_control.js

Before:
After:
Changes:
- Above fix for page headers in dark mode
- Changes the tag input bg highlighting to a CSS animation in order to better maintain readability of the tag name
- In dark mode uses an outline box-shadow instead of bg highlight for post nav buttons
- Darkens darktheme.message.success bg for readability contrast

Client CSS: Dark mode contrast fixes

---

.pre-commit-config.yaml
client/Dockerfile

- `npm i -g npm@lts` (in client/Dockerfile) is no longer valid as per https://github.com/npm/cli/wiki/Support-Policy#long-term-support-lts
- updated pre-commit config to use latest repos
the commit message somehow omitted `npm i -g npm@lts`, weird

updated build files

---

client/js/util/markdown.js

Removes the URL rewriting logic from the markdown handler, as discussed in #429
Fixes stuff like `[Really cool art!](https://booru.example.com/post/1337)` being rewritten to `[Really cool art!](https://booru.example.com@1337)`
Technically speaking this is a breaking change.

client: remove URL rewriting from the markdown handler

---

doc/API.md

While taking a look at szurubooru's code I noticed that `/post/<id>/around` is not documented, even though it is part of the API used by the frontend to power the previous/next post cursor.

doc: add GET /post/<id>/around to API.md

---

doc/API.md

The API documentation says a micro post contains the fields  "name" and "thumbnailUrl", which is wrong. Instead of "name", it should be "id".

docs (api): change micro post attribute name to id

---

README.md
doc/API.md
server/Dockerfile
server/requirements.txt
server/szurubooru/func/net.py

youtube-dl no longer even gets URLs properly:
```
⌁ [zakame:~/src/szurubooru] use-yt-dlp(1) 4s ± docker run --rm -it szurubooru/server:2.5 sh                                                                
Unable to find image 'szurubooru/server:2.5' locally
2.5: Pulling from szurubooru/server
Digest: sha256:4fa5bc78cc0c44632085adea92639346a151c8cc3023abbc0beb52f0f178f778
Status: Downloaded newer image for szurubooru/server:2.5
~ $ youtube-dl --version
2021.12.17
~ $ youtube-dl --format best --no-playlist --get-url https://www.youtube.com/watch?v=dQw4w9WgXcQ
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag …
```

server/net: use yt-dlp instead of youtube-dl

---

client/css/core-general.styl

Fixes ugly scrollbar appearing on the posts page when a post with extremely wide image/video is present in the list.
Before:
After:

Posts page ugly horizontal bar fix.

---

client/css/post-list-view.styl
client/css/post-main-view.styl
client/html/index.htm
client/html/post_main.tpl
client/html/posts_header.tpl
client/js/controls/post_content_control.js

Reordered mobile layout to have controls right below the picture
Before
After
Bulk tagging mobile layout
Before
After
Allow zooming in

Mobile improvements

---

client/js/controllers/pool_controller.js
client/js/controllers/post_main_controller.js
client/js/controllers/tag_controller.js
client/js/controllers/user_controller.js
client/js/controls/post_edit_sidebar_control.js
client/js/models/post.js

This fixes some crashes.
`_newPostThumbnail`/`_newThumbnail` is a special case where we should allow null for clearing on-server custom thumbnails, but it was previously crashing anyway because of a deeper rooted issue.  
That's addressed in #646. In this PR the initial state just does nothing instead of crashing.

client: add null checks

---

client/css/comment-control.styl

`break-all` makes it hard to read actual comments, e.g.
vs

client/css: fix comment word-break

---

client/js/controls/file_dropper_control.js

A few small issues.
This could be fixed by changing `this._urlInputNode.addEventListener("paste", ...)` to `window.onpaste = ...;`, but it feels a bit dirty to  touch the window. We can't use `window.addEventListener` because I don't think we have an 'unmounted' event where we can call `removeEventListener`. Though the same is true when using `window.onpaste`, but at least then it wouldn't add duplicate listeners when mounting the upload view multiple times (happens when navigating from upload -> another page -> upload again).
Because it wouldn't fit. Any suggestions?
How it is now:
How it would be with the change:
This doesn't work when the user has some privacy settings enabled (though at that point it also wouldn't work on imgur etc). I wouldn't know which specific setting. It doesn't …

Upload from clipboard

---

server/szurubooru/config.py

Allow running in Kubernetes, podman, and LXC, besides plain docker-compose,
without having to fake out /.dockerenv in non-Docker environments.

server/config: generalize container support

---

client/html/post_readonly_sidebar.tpl

Hello,
for a while now the Google Images search on the post details doesn't work anymore. I updated the template to link to the new Google Lens URL. I am using this fix for quiet some time now, so I can ensure it works without any problems.

Fixed the google search option in the post details view

---

client/.dockerignore
client/Dockerfile
client/build.js
client/docker-start-dev.sh
client/docker-start.sh
client/js/main.js
docker-compose.dev.yml
server/Dockerfile
server/docker-start-dev.sh

Earlier, [neobooru started work](https://github.com/neobooru/szurubooru/blob/docker-development-setup) to create a `docker-compose.dev.yml` for rapid hot-reloadable development in response to #395.
This commit should cleanly merge `docker-development-setup` into the current `master`, adding and fixing anything missing while keeping the scope of the change as small as possible.
Compared to downstream's branch, this commit
* Excludes extraneous changes such as
* Any formatting
* The use of [deprecated](https://docs.docker.com/reference/compose-file/version-and-name/)/ineffectual top-level `version:` in composer files
* Supports controlling `$THREADS`
* Respects currently used `FROM` statements, yadayada
The volume mounting setup during the `client, target development` Docker build step …

build: create docker-compose.dev.yml so dev build iteration doesn't take forever

---

client/html/help_comments.tpl
client/js/util/markdown.js

(Original discussion at #738)
Simple changes to markdown engine to allow use of an [icon]...[/icon] tag to insert an icon alongside a link.
This was inspired by danbooru artist pages, which have an easily recognizable icon on the left of the artist's social links, making it way easier to find the links one's looking for. Manually doing this for each artist would be a very tedious matter on a szurubooru instance, so I introduced this tag.
For example, putting [icon]https://www.youtube.com/watch?v=dQw4w9WgXcQ[/icon] in a markdown section gets it rendered as
https://www.youtube.com/watch?v=dQw4w9WgXcQ https://www.youtube.com/watch?v=dQw4w9WgXcQ.
Huge thanks to @po5 for help with the original PR!

client/markdown: add tag to show favicon alongside URL

---

client/js/util/markdown.js
client/js/util/misc.js

Introduced in 0137cf383a81e0a2a0f5db7c2ded4b4a55c5e2fc, anywhere that allows markdown e.g. comments allowed any arbitrary tag that wasn't explicitly banned by DOMPurify, since it cannot know whether it came from our Markdown renderer or from the user.
People could add arbitrary <style> tags that mess with the page, \<button>s etc. It did not lead to XSS since DOMPurify strips it, but still unacceptable.
Also, the sanitize function inside createRenderer had a broken regex and wouldn't actually sanitize anything, it's now replaced with our existing (and working) function.
escapeHtml is identical to the old behavior of marked.js sanitize=true
Had to move the function from misc.js into markdown.js to avoid circular imports.
I want to replace all HTML handling with modern DOM operations in a …

client/markdown: prevent arbitrary HTML

---

client/js/api.js
client/js/controllers/post_main_controller.js
client/js/models/post.js
client/js/models/post_list.js
client/js/util/misc.js

Makes switching between previous/next posts instant by prefilling the internal request cache for API requests, and loading image contents into the browser cache.

Preload nearby posts

---

server/szurubooru/rest/app.py

Some routes that address things by name instead of ID, e.g. /tag/tagname, where we allow special characters, need params to be unescaped.
For example a tag of `[test]` gets encoded by the frontend into `/tag/%5Btest%5D`, you can find this link in the tag listing. (/tags)
Previously, we would get an error saying `Tag ‘%5Btest%5D’ not found.`
We allow any non-space character inside of tag names, so decode them properly.
I don't believe this negatively affects any other part of the code, and it doesn't affect SEO (I was worried about duplicate pages but turns out even Github allows unnecessarily url encoded paths so it shouldn't be an issue).

server/rest: unescape percent-encoded route parameters

---

server/szurubooru/func/tags.py

cf. #521, #390
Previously this check was only done on the client. The API operates on tag slugs, and these special strings cause issues with web servers.

server/tags: prevent creation of "." and ".." tags

---

server/szurubooru/func/pool_categories.py
server/szurubooru/func/pools.py
server/szurubooru/func/tag_categories.py
server/szurubooru/func/tags.py
server/szurubooru/func/users.py
server/szurubooru/func/util.py
server/szurubooru/search/parser.py

cf. #669
Previously it would incorrectly allow strings with a trailing newline.
```
>>> re.match(r"^\S+$", "test\n")
<re.Match object; span=(0, 4), match='test'>
```

server: properly enforce validation regex

---

client/css/core-forms.styl
client/js/controllers/pool_list_controller.js
client/js/controllers/tag_list_controller.js
client/js/controls/auto_complete_control.js
client/js/controls/pool_auto_complete_control.js
client/js/controls/tag_auto_complete_control.js
client/js/controls/tag_input_control.js
client/js/models/pool_list.js
client/js/models/tag_list.js
client/js/util/misc.js
client/js/views/home_view.js
client/js/views/pool_merge_view.js
client/js/views/pools_header_view.js
client/js/views/posts_header_view.js
client/js/views/tag_merge_view.js
client/js/views/tags_header_view.js

- Autocompletion for negated tags (fixes #432)
- Better behavior for autocomplete in the middle of an already typed tag (replace current word, old behavior would split tag names down the middle)
- More sensible cursor positions after autocomplete (previously would always jump to the end even when completing from the middle of the query)
- Autocomplete the tag alias the user actually searched for (previously it would always use the first alias, which is confusing)
- Don't flash the progress indicator for tag/pool name autocomplete

Autocomplete tweaks
