- public_html/js/Presenters/PagerPresenter.js
- public_html/js/Presenters/PostPresenter.js
- public_html/templates/help.tpl
Added support for navigation using arrow keys.
> Added arrow keys support

- INSTALL.md
`postgres` package does not exist.
> Fixed dependency name

- server/szurubooru/api/password_reset_api.py
It is currently possible to perform a timing attack on the password reset api, since the `token` is compared to the `good_token` in a manner that takes variable time depending on how many of the first characters in `token` are correct.
This patches the vulnerability by having the timing depend on whether or not the md5 hashes start with the same character, instead of the tokens directly. Another possible fix would be to use a constant time algorithm for comparing strings.
> Patch timing attack

- config.yaml.dist
- server/szurubooru/api/post_api.py
- server/szurubooru/func/images.py
- server/szurubooru/func/mime.py
- server/szurubooru/func/posts.py
- server/szurubooru/func/util.py
* webm conversion is slow, but better quality than mp4 conversion with a typically smaller file size
* tags are copied over from the original upload
* Snapshots are generated for the new auto posts
* Default setting is false for both conversions, as this will require additional resources of the server, but is bandwidth friendly for viewers
> Added auto conversion options to the config for gif to mp4 and webm

- .gitignore
- INSTALL-OLD.md
- INSTALL.md
- README.md
- client/.dockerignore
- client/Dockerfile
- client/nginx.conf.docker
- docker-compose.yml.example
- server/.dockerignore
- server/Dockerfile
- server/config.yaml.dist
- server/szurubooru/config.py
- server/wait-for-es
Closes #169 
Mostly new files, so there shouldn't be any conflicts with other deployment methods. Only real file change is in `config.py`, which should smartly detect if it's running inside a container and pull some stuff from environment variables, and shouldn't affect anyone running it outside Docker.
The only real point of concern is ffmpeg. I elected to build a slimmed down copy inside the Dockerfile, instead of using a debian package. It takes a lot longer to build, but saves about 150MB in final image size buy cutting out useless stuff like HEVC, subtitle codecs, etc. And if you don't clear the build cache, you usually won't have to rebuild it, even when you rebuild the rest of the image.
I don't really have a strong opinion on this though, so if you think using packages is better, …
> Added Docker functionality

- INSTALL.md
- docker-compose.yml.example
> docker: Clarify required version numbers

- server/szurubooru/func/images.py
- server/szurubooru/func/posts.py
Fixes #221 . Seems to fix #225 but it's hard to tell what exactly caused the original bug in the first place.
> Bugfixes to #221 and #225

- client/js/views/tag_categories_view.js
> client/tag_categories: lowercase all color input on tag_categories

- client/js/controllers/post_upload_controller.js
> client/upload: automatically set source when uploading from url

- doc/API.md
- server/config.yaml.dist
- server/szurubooru/facade.py
- server/szurubooru/func/net.py
- server/szurubooru/func/snapshots.py
- server/szurubooru/tests/api/test_pool_category_updating.py
- server/szurubooru/tests/api/test_pool_creating.py
- server/szurubooru/tests/api/test_pool_deleting.py
- server/szurubooru/tests/api/test_post_creating.py
- server/szurubooru/tests/api/test_post_featuring.py
- server/szurubooru/tests/api/test_tag_category_updating.py
- server/szurubooru/tests/api/test_tag_creating.py
- server/szurubooru/tests/api/test_tag_deleting.py
- server/szurubooru/tests/func/test_net.py
- server/szurubooru/tests/func/test_snapshots.py
> server: API support for webhooks

- doc/API.md
Update documentation to match existing functionality.
> doc/api: add pools to post resource

- doc/API.md
- server/szurubooru/func/pools.py
- server/szurubooru/func/posts.py
- server/szurubooru/tests/func/test_posts.py
> server/pools: serialize pools as micro resource within post resources

- client/css/post-list-view.styl
- client/html/posts_page.tpl
- client/html/settings.tpl
- client/js/controllers/post_list_controller.js
- client/js/models/settings.js
- client/js/views/settings_view.js
> client/posts: support content aware post flow option

- install.sh
This pull request is meant to provide a user friendly install.sh for deploying Szurubooru.
Features:
- Prompts user for config values, then deploys Szurubooru automatically
- Performs the necessary ownership change of the local /data/ mount point to avoid problems uploading images #216 
- Checks host architecture and automates the changes outlined in readme.md and kaijuagenda's rpi3 fork for ARM hosts
I'm a big fan of documentation, so I tried my best to detail the purpose of the various operations and functions via comments. Naturally, these can be changed or removed if found to be too verbose or unclear.
> Docker: add installer.sh

- client/css/post-list-view.styl
- client/html/posts_header.tpl
- client/html/posts_page.tpl
- client/js/controllers/post_list_controller.js
- client/js/views/posts_header_view.js
- client/js/views/posts_page_view.js
- server/config.yaml.dist
Implement feature request #456
> client: add bulk delete feature

- server/szurubooru/search/configs/post_search_config.py
- server/szurubooru/tests/search/configs/test_post_search_config.py
Work in progress, my SQL is a bit rusty.
Fixes #438
> server: post category filter

- client/css/comment-control.styl
> fix overflow on comments, prevents ugly unnecesary horizontal scroll

- client/js/controllers/pool_list_controller.js
> Fix Pool Search

- client/css/core-general.styl
- client/css/user-list-view.styl
- client/html/post_readonly_sidebar.tpl
- client/js/util/views.js
Better fallbacks for deleted resources and sizing fixes.
> Better links

- client/css/post-main-view.styl
Fixes 4b6b231fc809b173f7f619563589e4eed77d35c2 from #641 that had a change from my personal fork (8acaf65f7baa80ff2412a3bcb0a8eca8d1bd4b60) carried over by accident.
> client/css: revert accidental style removal

- client/html/comment.tpl
- server/szurubooru/api/comment_api.py
- server/szurubooru/func/posts.py
- server/szurubooru/func/snapshots.py
- server/szurubooru/func/users.py
- server/szurubooru/migrations/versions/5b5c940b4e78_make_featuring_users_nullable.py
- server/szurubooru/model/comment.py
- server/szurubooru/model/post.py
Fixes the error described in #682
Tag creation worked for new posts by anonymous users, but not with new tags on an existing post.
Also allow anonymous users to feature posts and leave comments.
> Anon fixes
